{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    mpv
    easyeffects
    calibre
    audacity
    ghidra-bin
    gimp
    iaito
    tor-browser
    brave
    inputs.firefox-nightly.packages.${pkgs.system}.firefox-nightly-bin
    inputs.walker.packages.${pkgs.system}.default
    kodi-wayland
    alacritty
    kitty
    wezterm
    #ghostty
    inputs.ghostty.packages.${pkgs.system}.ghostty #builds from git
    nicotine-plus
    xournalpp
    pavucontrol
    #vesktop
    (vesktop.override {electron = pkgs.electron_35;})
    (discord-canary.override {
      withOpenASAR = true;
      withVencord = true;
    })
    transmission-remote-gtk
    (pkgs.wrapOBS {
      plugins = with pkgs.obs-studio-plugins; [
        wlrobs
        obs-backgroundremoval
        obs-pipewire-audio-capture
      ];
    })
    mkvtoolnix
    handbrake

    inputs.pwndbg.packages.${pkgs.stdenv.hostPlatform.system}.pwndbg
    inputs.pwndbg.packages.${pkgs.stdenv.hostPlatform.system}.pwndbg-lldb
    lm_sensors
    unzrip
    yara-x
    lynis
    lf
    _7zz-rar
    debootstrap
    arch-install-scripts
    shellcheck
    lazygit
    gammastep
    imv
    swayimg
    speedtest-rs
    speedtest-go
    weechat
    megatools
    socat
    netcat-openbsd
    nvme-cli
    pciutils
    usbutils
    mktorrent
    gef
    gdb
    lldb
    ncmpcpp
    rmpc
    libimobiledevice
    idevicerestore
    ugrep
    lsiutil
    btop
    torsocks
    bottom
    dosfstools
    ntfsprogs
    exfatprogs
    xfsprogs
    jfsutils
    modprobed-db
    yt-dlp
    ffmpegthumbnailer
    ctpv
    pngcrush
    gifsicle
    exiftool
    binwalk
    bomber-go
    sbomnix
    rustscan
    hashcat
    hashcat-utils
    mediainfo
    hledger
    hledger-ui
    hledger-utils
    hledger-iadd
    plan9port
  ];
}
