{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    easyeffects
    calibre
    audacity
    ghidra-bin
    gimp
    iaito
    tor-browser
    brave
    inputs.firefox-nightly.packages.${pkgs.system}.firefox-nightly-bin
    inputs.walker.packages.${pkgs.system}.default
    kodi-wayland
    alacritty
    kitty
    wezterm
    ghostty
    nicotine-plus
    xournalpp
    pavucontrol
    #Currently necessary for screen sharing
    #(vesktop.override {
    #  electron = pkgs.electron_32;
    #})
    vesktop
    transmission-remote-gtk
    (pkgs.wrapOBS {
      plugins = with pkgs.obs-studio-plugins; [
        wlrobs
        obs-backgroundremoval
        obs-pipewire-audio-capture
      ];
    })
    mkvtoolnix
    handbrake

    inputs.pwndbg.packages.${pkgs.stdenv.hostPlatform.system}.pwndbg
    inputs.pwndbg.packages.${pkgs.stdenv.hostPlatform.system}.pwndbg-lldb
    lm_sensors
    unzrip
    yara-x
    lynis
    lf
    _7zz-rar
    debootstrap
    shellcheck
    lazygit
    gammastep
    imv
    swayimg
    speedtest-rs
    speedtest-go
    weechat
    megatools
    socat
    netcat-openbsd
    mg
    nvme-cli
    pciutils
    usbutils
    mktorrent
    gef
    gdb
    lldb
    ncmpcpp
    rmpc
    libimobiledevice
    idevicerestore
    ugrep
    lsiutil
    btop
    torsocks
    bottom
    dosfstools
    ntfsprogs
    exfatprogs
    xfsprogs
    jfsutils
    modprobed-db
    yt-dlp
    #pamixer - broken
    ffmpegthumbnailer
    ctpv
    pngcrush
    gifsicle
    exiftool
    binwalk
    bomber-go
    sbomnix
    rustscan
    hashcat
    hashcat-utils
  ];
}
