# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.mylanguage]
# Command to execute
command = "nixfmt"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.nix" ]
# Glob patterns of files to exclude
excludes = []
# Controls the order of application when multiple formatters match the same file
# Lower the number, the higher the precedence
# Default is 0
priority = 0
