{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    easyeffects
    calibre
    protonup-ng
    audacity
    ghidra-bin
    gimp
    iaito
    tor-browser
    brave
    inputs.firefox-nightly.packages.${pkgs.system}.firefox-nightly-bin
    inputs.walker.packages.${pkgs.system}.default
    kodi-wayland
    alacritty
    wezterm
    ghostty
    nicotine-plus
    xournalpp
    pavucontrol
#Currently necessary for screen sharing
    (vesktop.override {
      electron = pkgs.electron_32;
    })
    transmission-remote-gtk

    lm_sensors
    unzrip
    yara-x
    lynis
    lf
    _7zz-rar
    debootstrap
    shellcheck
    lazygit
    grim
    grimblast
    sway-contrib.grimshot
    gammastep
    imv
    speedtest-rs
    speedtest-go
    weechat
    megatools
    socat
    nvme-cli
    mktorrent
    gef
    swww
    wl-clipboard
    waybar
    slurp
    swaynotificationcenter
    wofi
    hyprshot
    ncmpcpp
    rmpc
    libimobiledevice
    idevicerestore
    ugrep
    lsiutil
    btop
    bottom
    dosfstools
    exfatprogs
    xfsprogs
    jfsutils
    modprobed-db
    yt-dlp
    pamixer
  ];
}
