{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    #GUI

    #CLI
    pkgs.android-tools
    pkgs.bat
    pkgs.btop
    pkgs.bzip3
    pkgs.cargo
    pkgs.carapace
    pkgs.cmake
    pkgs.coreutils
    pkgs.croc
    pkgs.fish
    pkgs.gifsicle
    pkgs.gnused
    pkgs.htop
    pkgs.idevicerestore
    pkgs.imagemagick
    pkgs.ipfs
    pkgs.kalker
    pkgs.libimobiledevice
    pkgs.megatools
    pkgs.meson
    pkgs.nh
    pkgs.nushell
    pkgs.openssh
    pkgs.pandoc
    pkgs.pngcrush
    pkgs.pngquant
    pkgs.rizin
    pkgs.sox
    pkgs.speedtest-cli
    pkgs.starship
    pkgs.tealdeer
    pkgs.testdisk
    pkgs.tmux
    pkgs.torsocks
    pkgs.unar
    pkgs.vulkan-headers
    pkgs.wavpack
    pkgs.weechat
    pkgs.yara
    pkgs.yt-dlp
  ];

  fonts.packages = [
    pkgs.ibm-plex
    pkgs.nerd-fonts.blex-mono
    pkgs.nerd-fonts.droid-sans-mono
    pkgs.nerd-fonts.hack
    pkgs.nerd-fonts.iosevka-term
    pkgs.nerd-fonts.jetbrains-mono
    pkgs.nerd-fonts.meslo-lg
    pkgs.nerd-fonts.mononoki
    pkgs.nerd-fonts.zed-mono
    pkgs.noto-fonts
    pkgs.plemoljp-nf
    pkgs.twitter-color-emoji
  ];
}
