font_family ZedMono Nerd Font Mono
font_size 11.0
enable_audio_bell	no
tab_bar_edge	bottom
tab_bar_style powerline

#Blurred backgrounds
background_blur 1
background_opacity 0.9
dynamic_background_opacity yes

# BEGIN_KITTY_THEME
# Wizzy Bright
include current-theme.conf
# END_KITTY_THEME
