[main]
font=ZedMono NF Medium:style=Medium:size=15
#font=Lilex Nerd Font:style=Regular:size=15
width=100
lines=16
icon-theme=Papirus-Dark
terminal=kitty
[colors]
background=0b1a24ff
text=b7cecdff
match=53babaff
selection=083449ff
selection-match=53babaff
selection-text=b7cecdff
border=119f98ff
